platform :ios, "9.0"


targetsArray = ['Bmob']

targetsArray.each do |t|
    target t do
        
        pod 'Masonry', '~> 1.0.1'
        
  		pod 'BmobSDK', '~> 2.0.1'
 	 	pod 'FMDBHelper', '~> 1.0.1'
        pod 'SVProgressHUD', '~> 2.1.2'
        
    end
end



